### ISSUE TITLE
error: next/document should not be imported outside of pages

### ISSUE THREAD

**Issue by pedromtec** [React-Avancado/boilerplate#613]
I was receiving this error when I run the `lint ` and `build`. 

I fixed it updating `eslint-config-next` version to `11.1.3-canary.7`

https://stackoverflow.com/questions/69061240/nextjs-importing-next-document-outside-of-pages-document-error

Should we update the boilerplate?

**Comment by willianjusten** [comment]
It's not recommended to update to canary, since it's not a stable version. If you're having this error, I recommend to ignore for now passing this rule:

```
"rules": {
    "@next/next/no-document-import-in-page": "off"
}
```
