### ISSUE TITLE
[Storybook] Assets não carregam ao executar o script "build-storybook"

### ISSUE THREAD

**Issue by artursilveiradev** [React-Avancado/boilerplate#619]
Fala pessoal,
Estou com um problema para carregar os assets no build do Storybook. Já estou passando a flag "-s ./public" no script "build-storybook" no package.json, mas ainda assim os assets não carregam. Verifiquei e o Storybook está copiando o conteúdo do diretório "public" para o diretório "storybook-static" corretamente. Tentei reproduzir esse mesmo problema clonando esse repositório e o resultado foi o mesmo, os assets não carregaram. Alguém já passou por esse problema?
![Screenshot from 2021-11-20 07-55-13](https://user-images.githubusercontent.com/93391443/142723809-87080646-d777-4ade-a61a-14f1c3cd9b2f.png)

**Comment by caiotracera** [comment]
Faaaala, @artursilveiradev. Beleza?

Não sei se você já resolveu o seu problema, mas a solução é bem simples: no arquivo `src/components/Main/index.tsx`, provavelmente o seu logo está dessa forma:

```tsx
<Logo
        src="/images/logo.svg"
        alt="Imagem de um átomo e React Avançado escrito ao lado"
      />
```

Para que pare de dar problema, basta remover o primeiro `/` no src, tanto no Logo quanto no Illustration. Ficará dessa forma:

```tsx
<Logo
        src="images/logo.svg"
        alt="Imagem de um átomo e React Avançado escrito ao lado"
      />

      <Title>{title}</Title>
      <Description>{description}</Description>

      <Illustration
        src="images/illustration.svg"
        alt="Um desenvolvedor de frente para uma tela com código"
      />
```

Além disso, ponto importante: a flag <b>-s</b> para indicar um diretório estático que deve ser servido foi depreciada (mais informações: https://storybook.js.org/docs/react/configure/images-and-assets#%EF%B8%8F-deprecated-serving-static-files-via-storybook-cli). Para fazer a configuração correta, basta adicionar a linha `staticDirs: ['../public'],` apontando para a pasta estática (https://storybook.js.org/docs/react/configure/images-and-assets#serving-static-files-via-storybook-configuration).

Espero ter ajudado, e fique à disposição para me chamar.
Abraços,
Caio.

**Comment by artursilveiradev** [comment]
> Faaaala, @artursilveiradev. Beleza?
> 
> Não sei se você já resolveu o seu problema, mas a solução é bem simples: no arquivo `src/components/Main/index.tsx`, provavelmente o seu logo está dessa forma:
> 
> ```tsx
> <Logo
>         src="/images/logo.svg"
>         alt="Imagem de um átomo e React Avançado escrito ao lado"
>       />
> ```
> 
> Para que pare de dar problema, basta remover o primeiro `/` no src, tanto no Logo quanto no Illustration. Ficará dessa forma:
> 
> ```tsx
> <Logo
>         src="images/logo.svg"
>         alt="Imagem de um átomo e React Avançado escrito ao lado"
>       />
> 
>       <Title>{title}</Title>
>       <Description>{description}</Description>
> 
>       <Illustration
>         src="images/illustration.svg"
>         alt="Um desenvolvedor de frente para uma tela com código"
>       />
> ```
> 
> Além disso, ponto importante: a flag -s para indicar um diretório estático que deve ser servido foi depreciada ([mais informações](https://storybook.js.org/docs/react/configure/images-and-assets#%EF%B8%8F-deprecated-serving-static-files-via-storybook-cli)). Para fazer a configuração correta, basta adicionar a linha `staticDirs: ['../public'],` apontando para a pasta estática ([link para a documentação](https://storybook.js.org/docs/react/configure/images-and-assets#serving-static-files-via-storybook-configuration)).
> 
> Espero ter ajudado, e fique à disposição para me chamar. Abraços, Caio.

Fala @caiotracera, era isso mesmo!
Valeu pela ajuda, cara!
